CATEGORY_VIP = "VIP"
CATEGORY_STANDARD = "Standard"
CATEGORY_BASIC = "Basic"
CATEGORY_FREE = "Free"
_CLASS_CATEGORY = (
    (CATEGORY_VIP, "VIP"),
    (CATEGORY_STANDARD, "Standard"),
    (CATEGORY_BASIC, "Basic"),
    (CATEGORY_FREE, "Free"),
)
