# Generated by Django 3.2 on 2023-01-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='4e5d2e47-9e7b-4c5f-b673-20724866c74b', on_delete=django.db.models.deletion.PROTECT, to='product_app.categoryproduct', verbose_name='Categoria'),
        ),
    ]
