# Generated by Django 3.2 on 2022-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="password",
            new_name="old_password",
        ),
    ]
